paths_read:
  path_to_randperm: "/Users/lauraporta/local_data/rotation/stimlus_randperm.mat"
  path_to_aux: "/Users/lauraporta/local_data/rotation/230802_CAA_1120182/aux_stim/230802_CAA_1120182_rotationincrement_1_001.bin"
  path_to_tif: "/Users/lauraporta/local_data/rotation/230802_CAA_1120182/imaging/rotation_increment_00001.tif"
paths_write:
  logs_folder: "/Users/lauraporta/local_data/rotation/230802_CAA_1120182/logs/"
  derotated_tiff_folder: "/Users/lauraporta/local_data/rotation/230802_CAA_1120182/"
  saving_name: "derotated_masked_full"


channel_names: [
    "camera",
    "scanimage_frameclock",
    "scanimage_lineclock",
    "photodiode2",
    "PI_rotON",
    "PI_rotticks",
]
rotation_increment: 0.2

adjust_increment: True
rot_deg: 360

debugging_plots: True

analog_signals_processing:
  find_rotation_ticks_peaks:
    height: 4
    distance: 20
  squared_pulse_k: 0
  inter_rotation_interval_min_len: 1000

interpolation:
  line_use_start: True
  frame_use_start: True
