paths:
  root:  "/Users/laura/data/derotation/raw/"
  # following two expected inside root folder
  path-to-randperm: "stimlus_randperm.mat"
  dataset-folder: "230802_CAA_1120182"
  # following two expected inside dataset-folder
  path-to-aux: "aux_stim/230802_CAA_1120182_rotation_1_001.bin"
  path-to-tif: "imaging/rotation_00001.tif"


rotation_increment: 0.2
channel_names: [
    "camera",
    "scanimage_frameclock",
    "scanimage_lineclock",
    "photodiode2",
    "PI_rotON",
    "PI_rotticks",
]
offset:  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
scale: [1.0, 1.0, 1.0, 1.0, 1.0, 1.0]
