"""
Full pipeline integration: simulate and find center of rotation
================================================================

This tutorial demonstrates the integration of the full derotation pipeline,
including simulation of a tilted rotation plane and the incremental search
for the center of rotation.

We will:
- Generate synthetic line-scanning image stacks.
- Simulate out-of-plane and oriented rotations.
- Run the complete `integration_pipeline()` to test derotation accuracy.
- Automatically display the plots generated by the pipeline.

"""

# %%
# Imports
# -------
from pathlib import Path

from IPython.display import Image, display

from derotation.simulate.synthetic_data import SyntheticData

# %%
# Define parameters for the synthetic simulation
# ----------------------------------------------

rotation_plane_angle = 25  # degrees
rotation_plane_orientation = 45  # degrees
center_of_rotation_offset = (20, -10)  # pixels

# %%
# Run full pipeline
# -----------------
# This will generate simulated rotated data and run an incremental search
# to find the optimal center of rotation.
# All intermediate plots are saved in the "debug" folder.

s_data = SyntheticData(
    radius=5,
    center_of_rotation_offset=center_of_rotation_offset,
    rotation_plane_angle=rotation_plane_angle,
    rotation_plane_orientation=rotation_plane_orientation,
    num_frames=50,
    pad=20,
    background_value=80,
    plots=True,
)

s_data.integration_pipeline()

# %%
# Display all debug plots
# -----------------------
# Let's display all `.png` files in the `debug/` folder, sorted by filename.

debug_folder = Path("debug")
debug_images = sorted(debug_folder.glob("*.png"))

print(f"Found {len(debug_images)} plots in debug/")

for img_path in debug_images:
    print(f"\n{img_path.name}")
    display(Image(filename=str(img_path)))
